### ISSUE TITLE
Constant deprecation in HA Core

### ISSUE THREAD

**Issue by true-bluey** [mihailescu2m/hass-airtouch4-platform#12]
Various constants used by airtouch4 have been deprecated 
![image](https://github.com/mihailescu2m/hass-airtouch4-platform/assets/54353376/c14fa61e-5efb-4a3b-a7f4-9dfad3086e6c)

`CURRENT_HVAC_IDLE`
`CURRENT_HVAC_FAN`
`SUPPORT_FAN_MODE`
`SUPPORT_TARGET_TEMPERATURE`
`SUPPORT_PRESET_MODE`

**Comment by sddgit** [comment]
Adding a voice. Also:

```
Entity None (<class 'custom_components.polyaire.climate.AirTouchACThermostat'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/mihailescu2m/hass-airtouch4-platform/issues
Entity None (<class 'custom_components.polyaire.climate.AirTouchACThermostat'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/mihailescu2m/hass-airtouch4-platform/issues
Entity None (<class 'custom_components.polyaire.climate.AirTouchACThermostat'>) implements HVACMode(s): off, cool, fan_only, dry, heat, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/mihailescu2m/hass-airtouch4-platform/issues
```
And
```
Entity None (<class 'custom_components.polyaire.climate.AirTouchACThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE: 9>, please create a bug report at https://github.com/mihailescu2m/hass-airtouch4-platform/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity None (<class 'custom_components.polyaire.fan.AirTouchGroupDamper'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|PRESET_MODE: 9>, please create a bug report at https://github.com/mihailescu2m/hass-airtouch4-platform/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by tomwaldnz** [comment]
I've also run into this problem. To keep using this component I have to lock HA to version 2025.12.5, or the component needs to be updated. Given the pull requests haven't been looked at in many months it might be that we have to move to a different component to control HA.  [This one](https://github.com/TheNoctambulist/hass-airtouch) is apparently actively maintained and is quite popular, but it would mean significantly rewriting dozens of automations I have.

@mihailescu2m do you have any plans to update this component, or will it be deprecated?

**Comment by sddgit** [comment]
I’ve switched to the integration you mentioned, and it works well. Can you not keep the same entity names so your automations aren’t upset?

**Comment by tomwaldnz** [comment]
> I’ve switched to the integration you mentioned, and it works well. Can you not keep the same entity names so your automations aren’t upset?

I don't know, I've never tried to change custom components. It looks like the way it models things is different. With this component you have a climate entity for each zone, plus you control damper percentages fan entity. With the new component it looks like you have a climate entity per air conditioner, climate entities for each zone (which might be the same as this one), but dampers are controlled using a "cover" entity.

This is an example of the kind of thing some of my automations do to set the damper percentages directly. I think this would need to be changed quite a bit to work with the other component.


```
  - data: {}
    target:
      entity_id:
        - fan.damper_guest
        - fan.damper_master
    action: fan.turn_off
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - data:
      preset_mode: Damper
    target:
      entity_id:
        - fan.damper_master
        - fan.damper_guest
    action: fan.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - data:
      percentage: 20
    target:
      entity_id: fan.damper_master
    action: fan.set_percentage
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - data:
      preset_mode: ITC
    target:
      entity_id:
        - fan.damper_master
        - fan.damper_guest
    action: fan.turn_on
```
